var card_dict = JSON.parse(
'[ '
+ '{ "name": "神秘精灵", "id": "142", "deck": "neutral", "row": "close", "strength": "0", "ability": "hero spy", "filename": "mysterious_elf", "count": "1" }'
+ ', { "name": "诱饵", "id": "1", "deck": "special", "row": "", "strength": "", "ability": "decoy", "filename": "decoy", "count": "3" }' 
+ ', { "name": "刺骨冰霜", "id": "4", "deck": "weather", "row": "", "strength": "", "ability": "frost", "filename": "frost", "count": "3" }'
+ ', { "name": "希里雅·菲欧娜·艾伦·丽安隆", "id": "139", "deck": "neutral", "row": "close", "strength": "15", "ability": "hero muster", "filename": "ciri", "count": "1", "muster": "萝卜" }'
+ ', { "name": "晴空", "id": "7", "deck": "weather", "row": "", "strength": "", "ability": "clear", "filename": "clear", "count": "3" }'
+ ', { "name": "指挥官号角", "id": "2", "deck": "special", "row": "", "strength": "", "ability": "horn", "filename": "horn", "count": "3" }'
+ ', { "name": "丹德里恩", "id": "11", "deck": "neutral", "row": "close", "strength": "2", "ability": "horn", "filename": "dandelion", "count": "1" }'
+ ', { "name": "艾米尔·雷吉斯·洛赫莱克·塔吉夫", "id": "", "deck": "neutral", "row": "close", "strength": "5", "ability": "", "filename": "emiel", "count": "1" }'
+ ', { "name": "利维亚的杰洛特", "id": "138", "deck": "neutral", "row": "close", "strength": "15", "ability": "hero muster", "filename": "geralt", "count": "1", "muster": "萝卜" }'
+ ', { "name": "蔽日浓雾", "id": "5", "deck": "weather", "row": "", "strength": "", "ability": "fog", "filename": "fog", "count": "3" }'
+ ', { "name": "灼烧", "id": "3", "deck": "special", "row": "", "strength": "", "ability": "scorch", "filename": "scorch", "count": "3" }'
+ ', { "name": "倾盆大雨", "id": "6", "deck": "weather", "row": "", "strength": "", "ability": "rain", "filename": "rain", "count": "3" }'
+ ', { "name": "特莉丝·梅莉葛德", "id": "141", "deck": "neutral", "row": "close", "strength": "7", "ability": "hero", "filename": "triss", "count": "1" }'
+ ', { "name": "维瑟米尔", "id": "9", "deck": "neutral", "row": "close", "strength": "6", "ability": "", "filename": "vesemir", "count": "1" }'
+ ', { "name": "维伦特瑞坦梅斯", "id": "8", "deck": "neutral", "row": "close", "strength": "7", "ability": "scorch_c", "filename": "villen", "count": "1" }'
+ ', { "name": "范格堡的叶奈法", "id": "140", "deck": "neutral", "row": "ranged", "strength": "7", "ability": "hero medic", "filename": "yennefer", "count": "1" }'
+ ', { "name": "卓尔坦·齐瓦", "id": "10", "deck": "neutral", "row": "close", "strength": "5", "ability": "", "filename": "zoltan", "count": "1" }'
+ ', { "name": "欧吉尔德·伊佛瑞克", "id": "", "deck": "neutral", "row": "agile", "strength": "6", "ability": "morale", "filename": "olgierd", "count": "1" }'
+ ', { "name": "刚特·欧迪姆", "id": "", "deck": "neutral", "row": "siege", "strength": "2", "ability": "muster", "filename": "gaunter_odimm", "count": "1" }'
+ ', { "name": "刚特·欧迪姆 — 黑暗", "id": "", "deck": "neutral", "row": "ranged", "strength": "4", "ability": "muster", "filename": "gaunter_odimm_darkness", "count": "3" }'
+ ', { "name": "奶牛", "id": "", "deck": "neutral", "row": "ranged", "strength": "0", "ability": "avenger", "filename": "cow", "count": "1" }'
+ ', { "name": "牛之防御部队", "id": "", "deck": "neutral", "row": "close", "strength": "8", "ability": "", "filename": "chort", "count": "0" }'
+ ', { "name": "弗尔泰斯特 — 泰莫利亚之王", "id": "5", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_king", "filename": "foltest_silver", "count": "1" }'
+ ', { "name": "弗尔泰斯特 — 北方大军统帅", "id": "8", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_lord", "filename": "foltest_gold", "count": "1" }'
+ ', { "name": "弗尔泰斯特 — 攻城大师", "id": "6", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_siegemaster", "filename": "foltest_copper", "count": "1" }'
+ ', { "name": "弗尔泰斯特 — 钢剑所铸", "id": "7", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_steelforged", "filename": "foltest_bronze", "count": "1" }'
+ ', { "name": "弗尔泰斯特 — 梅德尔之子", "id": "", "deck": "realms", "row": "leader", "strength": "", "ability": "foltest_son", "filename": "foltest_son_of_medell", "count": "1" }'
+ ', { "name": "弩炮", "id": "79", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "ballista", "count": "1" }'
+ ', { "name": "蓝衣铁卫突击队", "id": "92", "deck": "realms", "row": "close", "strength": "4", "ability": "bond", "filename": "blue_stripes", "count": "3" }'
+ ', { "name": "投石机", "id": "75", "deck": "realms", "row": "siege", "strength": "8", "ability": "bond", "filename": "catapult_1", "count": "2" }'
+ ', { "name": "科瑞法尔德猎龙人", "id": "87", "deck": "realms", "row": "ranged", "strength": "5", "ability": "bond", "filename": "crinfrid", "count": "3" }'
+ ', { "name": "德特莫德", "id": "76", "deck": "realms", "row": "ranged", "strength": "6", "ability": "", "filename": "dethmold", "count": "1" }'
+ ', { "name": "邓·班纳医生", "id": "88", "deck": "realms", "row": "siege", "strength": "5", "ability": "medic", "filename": "banner_nurse", "count": "1" }'
+ ', { "name": "艾斯特拉德·蒂森", "id": "11", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "esterad", "count": "1" }'
+ ', { "name": "约翰·纳塔利斯", "id": "10", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "natalis", "count": "1" }'
+ ', { "name": "科德温攻城专家", "id": "98", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege", "count": "1" }'
+ ', { "name": "科德温攻城专家", "id": "99", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege_1", "count": "1" }'
+ ', { "name": "科德温攻城专家", "id": "100", "deck": "realms", "row": "siege", "strength": "1", "ability": "morale", "filename": "kaedwen_siege_2", "count": "1" }'
+ ', { "name": "凯拉·梅兹", "id": "84", "deck": "realms", "row": "ranged", "strength": "5", "ability": "", "filename": "keira", "count": "1" }'
+ ', { "name": "菲丽芭·艾哈特", "id": "12", "deck": "realms", "row": "ranged", "strength": "10", "ability": "hero", "filename": "philippa", "count": "1" }'
+ ', { "name": "该死的步兵", "id": "95", "deck": "realms", "row": "close", "strength": "1", "ability": "bond", "filename": "poor_infantry", "count": "4" }'
+ ', { "name": "史登尼斯王子", "id": "86", "deck": "realms", "row": "close", "strength": "5", "ability": "spy", "filename": "stennis", "count": "1" }'
+ ', { "name": "瑞达尼亚步兵", "id": "96", "deck": "realms", "row": "close", "strength": "1", "ability": "", "filename": "redania", "count": "1" }'
+ ', { "name": "瑞达尼亚步兵", "id": "97", "deck": "realms", "row": "close", "strength": "1", "ability": "", "filename": "redania_1", "count": "1" }'
+ ', { "name": "谢尔顿·斯卡格斯", "id": "91", "deck": "realms", "row": "ranged", "strength": "4", "ability": "", "filename": "sheldon", "count": "1" }'
+ ', { "name": "攻城塔", "id": "81", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "siege_tower", "count": "1" }'
+ ', { "name": "丹尼斯的齐格菲", "id": "83", "deck": "realms", "row": "close", "strength": "5", "ability": "", "filename": "siegfried", "count": "1" }'
+ ', { "name": "西吉斯蒙德·迪科斯彻", "id": "89", "deck": "realms", "row": "close", "strength": "4", "ability": "spy", "filename": "dijkstra", "count": "1" }'
+ ', { "name": "席儿·德·坦沙维尔", "id": "85", "deck": "realms", "row": "ranged", "strength": "5", "ability": "", "filename": "sheala", "count": "1" }'
+ ', { "name": "塔勒", "id": "94", "deck": "realms", "row": "siege", "strength": "1", "ability": "spy", "filename": "thaler", "count": "1" }'
+ ', { "name": "萨宾娜·葛莱维希格", "id": "90", "deck": "realms", "row": "ranged", "strength": "4", "ability": "", "filename": "sabrina", "count": "1" }'
+ ', { "name": "弗农·罗契", "id": "9", "deck": "realms", "row": "close", "strength": "10", "ability": "hero", "filename": "vernon", "count": "1" }'
+ ', { "name": "薇丝", "id": "82", "deck": "realms", "row": "close", "strength": "5", "ability": "", "filename": "ves", "count": "1" }'
+ ', { "name": "亚尔潘·齐格林", "id": "93", "deck": "realms", "row": "close", "strength": "2", "ability": "", "filename": "yarpen", "count": "1" }'
+ ', { "name": "投石车", "id": "77", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "trebuchet", "count": "1" }'
+ ', { "name": "投石车", "id": "78", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "trebuchet_1", "count": "1" }'
+ ', { "name": "恩希尔·恩瑞斯 — 皇帝陛下", "id": "1", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_imperial", "filename": "emhyr_silver", "count": "1" }'
+ ', { "name": "恩希尔·恩瑞斯 — 尼弗迦德皇帝", "id": "2", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_emperor", "filename": "emhyr_copper", "count": "1" }'
+ ', { "name": "恩希尔·恩瑞斯 — 白色火焰", "id": "3", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_whiteflame", "filename": "emhyr_bronze", "count": "1" }'
+ ', { "name": "恩希尔·恩瑞斯 — 无情者", "id": "4", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_relentless", "filename": "emhyr_gold", "count": "1" }'
+ ', { "name": "恩希尔·恩瑞斯 — 北方入侵者", "id": "", "deck": "nilfgaard", "row": "leader", "strength": "", "ability": "emhyr_invader", "filename": "emhyr_invader_of_the_north", "count": "1" }'
+ ', { "name": "阿尔布里希", "id": "68", "deck": "nilfgaard", "row": "ranged", "strength": "2", "ability": "", "filename": "albrich", "count": "1" }'
+ ', { "name": "阿希尔·瓦·阿纳希德", "id": "52", "deck": "nilfgaard", "row": "ranged", "strength": "6", "ability": "", "filename": "assire", "count": "1" }'
+ ', { "name": "黑步弓兵", "id": "47", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "", "filename": "black_archer", "count": "1" }'
+ ', { "name": "黑步弓兵", "id": "48", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "", "filename": "black_archer_1", "count": "1" }'
+ ', { "name": "卡希尔·莫尔·迪夫林·爱普·塞拉克", "id": "54", "deck": "nilfgaard", "row": "close", "strength": "6", "ability": "", "filename": "cahir", "count": "1" }'
+ ', { "name": "辛西亚", "id": "60", "deck": "nilfgaard", "row": "ranged", "strength": "4", "ability": "", "filename": "cynthia", "count": "1" }'
+ ', { "name": "艾托利亚辅助弓兵", "id": "72", "deck": "nilfgaard", "row": "ranged", "strength": "1", "ability": "medic", "filename": "archer_support", "count": "1" }'
+ ', { "name": "艾托利亚辅助弓兵", "id": "73", "deck": "nilfgaard", "row": "ranged", "strength": "1", "ability": "medic", "filename": "archer_support_1", "count": "1" }'
+ ', { "name": "芙琳吉拉·薇歌", "id": "53", "deck": "nilfgaard", "row": "ranged", "strength": "6", "ability": "", "filename": "fringilla", "count": "1" }'
+ ', { "name": "重型泽瑞坎火蝎", "id": "49", "deck": "nilfgaard", "row": "siege", "strength": "10", "ability": "", "filename": "heavy_zerri", "count": "1" }'
+ ', { "name": "帝国军精锐卫队", "id": "67", "deck": "nilfgaard", "row": "close", "strength": "3", "ability": "bond", "filename": "imperal_brigade", "count": "4" }'
+ ', { "name": "古雷特的雷索", "id": "147", "deck": "nilfgaard", "row": "close", "strength": "10", "ability": "hero", "filename": "letho", "count": "1" }'
+ ', { "name": "门诺·库霍恩", "id": "148", "deck": "nilfgaard", "row": "close", "strength": "10", "ability": "hero medic", "filename": "menno", "count": "1" }'
+ ', { "name": "莫特森", "id": "64", "deck": "nilfgaard", "row": "close", "strength": "3", "ability": "", "filename": "morteisen", "count": "1" }'
+ ', { "name": "莫尔凡·沃里斯", "id": "149", "deck": "nilfgaard", "row": "siege", "strength": "10", "ability": "hero", "filename": "moorvran", "count": "1" }'
+ ', { "name": "纳乌西卡骑兵", "id": "71", "deck": "nilfgaard", "row": "close", "strength": "2", "ability": "bond", "filename": "nauzicaa_2", "count": "3" }'
+ ', { "name": "普特卡默", "id": "66", "deck": "nilfgaard", "row": "ranged", "strength": "3", "ability": "", "filename": "puttkammer", "count": "1" }'
+ ', { "name": "雷恩法恩", "id": "61", "deck": "nilfgaard", "row": "close", "strength": "4", "ability": "", "filename": "rainfarn", "count": "1" }'
+ ', { "name": "雷纳德·爱普·马森", "id": "56", "deck": "nilfgaard", "row": "ranged", "strength": "5", "ability": "", "filename": "renuald", "count": "1" }'
+ ', { "name": "腐朽投石机", "id": "65", "deck": "nilfgaard", "row": "siege", "strength": "3", "ability": "", "filename": "rotten", "count": "1" }'
+ ', { "name": "席拉德·菲茨-奥斯特伦", "id": "51", "deck": "nilfgaard", "row": "close", "strength": "7", "ability": "spy", "filename": "shilard", "count": "1" }'
+ ', { "name": "攻城工程师", "id": "55", "deck": "nilfgaard", "row": "siege", "strength": "6", "ability": "", "filename": "siege_engineer", "count": "1" }'
+ ', { "name": "攻城技师", "id": "74", "deck": "nilfgaard", "row": "siege", "strength": "0", "ability": "medic", "filename": "siege_support", "count": "1" }'
+ ', { "name": "斯特凡·史凯伦", "id": "50", "deck": "nilfgaard", "row": "close", "strength": "9", "ability": "spy", "filename": "stefan", "count": "1" }'
+ ', { "name": "施维尔", "id": "69", "deck": "nilfgaard", "row": "ranged", "strength": "2", "ability": "", "filename": "sweers", "count": "1" }'
+ ', { "name": "提伯·艾格布拉杰", "id": "150", "deck": "nilfgaard", "row": "ranged", "strength": "10", "ability": "hero", "filename": "tibor", "count": "1" }'
+ ', { "name": "凡赫玛", "id": "62", "deck": "nilfgaard", "row": "ranged", "strength": "4", "ability": "", "filename": "vanhemar", "count": "1" }'
+ ', { "name": "瓦提尔·德·李道克斯", "id": "63", "deck": "nilfgaard", "row": "close", "strength": "4", "ability": "spy", "filename": "vattier", "count": "1" }'
+ ', { "name": "弗雷姆德", "id": "70", "deck": "nilfgaard", "row": "close", "strength": "2", "ability": "", "filename": "vreemde", "count": "1" }'
+ ', { "name": "年轻使节", "id": "58", "deck": "nilfgaard", "row": "close", "strength": "5", "ability": "bond", "filename": "young_emissary", "count": "1" }'
+ ', { "name": "年轻使节", "id": "59", "deck": "nilfgaard", "row": "close", "strength": "5", "ability": "bond", "filename": "young_emissary_1", "count": "1" }'
+ ', { "name": "泽瑞坎火蝎", "id": "57", "deck": "nilfgaard", "row": "siege", "strength": "5", "ability": "", "filename": "zerri", "count": "1" }'
+ ', { "name": "艾瑞汀 — 红骑士指挥官", "id": "134", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_commander", "filename": "eredin_silver", "count": "1" }'
+ ', { "name": "艾瑞汀 — 死亡使者", "id": "136", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_bringer_of_death", "filename": "eredin_bronze", "count": "1" }'
+ ', { "name": "艾瑞汀 — 灭世者", "id": "137", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_destroyer", "filename": "eredin_gold", "count": "1" }'
+ ', { "name": "艾瑞汀 — 狂猎之王", "id": "135", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_king", "filename": "eredin_copper", "count": "1" }'
+ ', { "name": "艾瑞汀·布雷阿克·格拉斯 — 背信者", "id": "", "deck": "monsters", "row": "leader", "strength": "", "ability": "eredin_treacherous", "filename": "eredin_the_treacherous", "count": "1" }'
+ ', { "name": "蟹蜘蛛", "id": "27", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas", "count": "1" }'
+ ', { "name": "蟹蜘蛛", "id": "28", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas_1", "count": "1" }'
+ ', { "name": "蟹蜘蛛", "id": "29", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "arachas_2", "count": "1" }'
+ ', { "name": "蟹蜘蛛巨兽", "id": "15", "deck": "monsters", "row": "siege", "strength": "6", "ability": "muster", "filename": "arachas_behemoth", "count": "1" }'
+ ', { "name": "尸婴", "id": "26", "deck": "monsters", "row": "close", "strength": "4", "ability": "", "filename": "poroniec", "count": "1" }'
+ ', { "name": "塞拉诺鹰身女妖", "id": "38", "deck": "monsters", "row": "agile", "strength": "2", "ability": "", "filename": "celaeno_harpy", "count": "1" }'
+ ', { "name": "鸡蛇兽", "id": "36", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "cockatrice", "count": "1" }'
+ ', { "name": "老巫妪 — 煮婆", "id": "16", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen", "count": "1" }'
+ ', { "name": "老巫妪 — 织婆", "id": "17", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen_1", "count": "1" }'
+ ', { "name": "老巫妪 — 呢喃婆", "id": "18", "deck": "monsters", "row": "close", "strength": "6", "ability": "muster", "filename": "witch_velen_2", "count": "1" }'
+ ', { "name": "战灵", "id": "143", "deck": "monsters", "row": "close", "strength": "10", "ability": "hero", "filename": "draug", "count": "1" }'
+ ', { "name": "土元素", "id": "12", "deck": "monsters", "row": "siege", "strength": "6", "ability": "", "filename": "earth_elemental", "count": "1" }'
+ ', { "name": "安德莱格", "id": "34", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "endrega", "count": "1" }'
+ ', { "name": "魔像", "id": "13", "deck": "monsters", "row": "close", "strength": "6", "ability": "", "filename": "fiend", "count": "1" }'
+ ', { "name": "火元素", "id": "14", "deck": "monsters", "row": "siege", "strength": "6", "ability": "", "filename": "fire_elemental", "count": "1" }'
+ ', { "name": "雾灵", "id": "39", "deck": "monsters", "row": "close", "strength": "2", "ability": "", "filename": "fogling", "count": "1" }'
+ ', { "name": "叉尾龙", "id": "19", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "forktail", "count": "1" }'
+ ', { "name": "怖客", "id": "23", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "frightener", "count": "1" }'
+ ', { "name": "石像鬼", "id": "37", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "gargoyle", "count": "1" }'
+ ', { "name": "食尸鬼", "id": "44", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul", "count": "1" }'
+ ', { "name": "食尸鬼", "id": "45", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul_1", "count": "1" }'
+ ', { "name": "食尸鬼", "id": "46", "deck": "monsters", "row": "close", "strength": "1", "ability": "muster", "filename": "ghoul_2", "count": "1" }'
+ ', { "name": "墓穴女巫", "id": "25", "deck": "monsters", "row": "ranged", "strength": "5", "ability": "", "filename": "gravehag", "count": "1" }'
+ ', { "name": "狮鹫", "id": "21", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "gryffin", "count": "1" }'
+ ', { "name": "鹰身女妖", "id": "35", "deck": "monsters", "row": "agile", "strength": "2", "ability": "", "filename": "harpy", "count": "1" }'
+ ', { "name": "冰巨人", "id": "24", "deck": "monsters", "row": "siege", "strength": "5", "ability": "", "filename": "frost_giant", "count": "1" }'
+ ', { "name": "伊勒瑞斯", "id": "144", "deck": "monsters", "row": "close", "strength": "10", "ability": "hero", "filename": "imlerith", "count": "1" }'
+ ', { "name": "柯兰", "id": "146", "deck": "monsters", "row": "agile", "strength": "8", "ability": "hero morale", "filename": "kayran", "count": "1" }'
+ ', { "name": "树精", "id": "145", "deck": "monsters", "row": "ranged", "strength": "10", "ability": "hero", "filename": "leshen", "count": "1" }'
+ ', { "name": "水鬼", "id": "41", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker", "count": "1" }'
+ ', { "name": "水鬼", "id": "42", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker_1", "count": "1" }'
+ ', { "name": "水鬼", "id": "43", "deck": "monsters", "row": "close", "strength": "2", "ability": "muster", "filename": "nekker_2", "count": "1" }'
+ ', { "name": "瘟疫少女", "id": "20", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "mighty_maiden", "count": "1" }'
+ ', { "name": "吸血鬼 — 布鲁莎", "id": "33", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "bruxa", "count": "1" }'
+ ', { "name": "吸血鬼 — 埃吉玛拉", "id": "30", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "ekkima", "count": "1" }'
+ ', { "name": "吸血鬼 — 弗莱德", "id": "31", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "fleder", "count": "1" }'
+ ', { "name": "吸血鬼 — 格卡因", "id": "32", "deck": "monsters", "row": "close", "strength": "4", "ability": "muster", "filename": "garkain", "count": "1" }'
+ ', { "name": "吸血鬼 — 卡塔坎", "id": "", "deck": "monsters", "row": "close", "strength": "5", "ability": "muster", "filename": "katakan", "count": "1" }'
+ ', { "name": "狼人", "id": "22", "deck": "monsters", "row": "close", "strength": "5", "ability": "", "filename": "werewolf", "count": "1" }'
+ ', { "name": "双足飞龙", "id": "40", "deck": "monsters", "row": "ranged", "strength": "2", "ability": "", "filename": "wyvern", "count": "1" }'
+ ', { "name": "癞蛤蟆", "id": "", "deck": "monsters", "row": "ranged", "strength": "7", "ability": "scorch_r", "filename": "toad", "count": "1" }'
+ ', { "name": "法兰茜丝卡·芬达贝 — 多尔·布雷坦纳女王", "id": "13", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_queen", "filename": "francesca_silver", "count": "1" }'
+ ', { "name": "法兰茜丝卡·芬达贝 — 美人", "id": "14", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_beautiful", "filename": "francesca_gold", "count": "1" }'
+ ', { "name": "法兰茜丝卡·芬达贝 — 山谷雏菊", "id": "15", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_daisy", "filename": "francesca_copper", "count": "1" }'
+ ', { "name": "法兰茜丝卡·芬达贝 — 纯血精灵", "id": "16", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_pureblood", "filename": "francesca_bronze", "count": "1" }'
+ ', { "name": "法兰茜丝卡·芬达贝 — 艾恩·希德的希望", "id": "", "deck": "scoiatael", "row": "leader", "strength": "", "ability": "francesca_hope", "filename": "francesca_hope_of_the_aen_seidhe", "count": "1" }'
+ ', { "name": "基兰·爱普·厄斯尼利恩", "id": "122", "deck": "scoiatael", "row": "agile", "strength": "3", "ability": "", "filename": "ciaran", "count": "1" }'
+ ', { "name": "巴克莱·艾尔斯", "id": "106", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "barclay", "count": "1" }'
+ ', { "name": "丹尼斯·克兰默", "id": "102", "deck": "scoiatael", "row": "close", "strength": "6", "ability": "", "filename": "dennis", "count": "1" }'
+ ', { "name": "多尔·布雷坦纳弓兵", "id": "121", "deck": "scoiatael", "row": "ranged", "strength": "4", "ability": "", "filename": "dol_archer", "count": "1" }'
+ ', { "name": "多尔·布雷坦纳侦察兵", "id": "107", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry", "count": "1" }'
+ ', { "name": "多尔·布雷坦纳侦察兵", "id": "108", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry_1", "count": "1" }'
+ ', { "name": "多尔·布雷坦纳侦察兵", "id": "109", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "dol_infantry_2", "count": "1" }'
+ ', { "name": "矮人斥候", "id": "123", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf", "count": "1" }'
+ ', { "name": "矮人斥候", "id": "124", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf_1", "count": "1" }'
+ ', { "name": "矮人斥候", "id": "125", "deck": "scoiatael", "row": "close", "strength": "3", "ability": "muster", "filename": "dwarf_2", "count": "1" }'
+ ', { "name": "伊丝妮", "id": "17", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "eithne", "count": "1" }'
+ ', { "name": "精灵斥候", "id": "127", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher", "count": "1" }'
+ ', { "name": "精灵斥候", "id": "128", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher_1", "count": "1" }'
+ ', { "name": "精灵斥候", "id": "129", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "muster", "filename": "elf_skirmisher_2", "count": "1" }'
+ ', { "name": "菲拉凡德瑞·艾恩·菲岱尔", "id": "104", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "filavandrel", "count": "1" }'
+ ', { "name": "哈维卡医者", "id": "131", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse", "count": "1" }'
+ ', { "name": "哈维卡医者", "id": "132", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse_1", "count": "1" }'
+ ', { "name": "哈维卡医者", "id": "133", "deck": "scoiatael", "row": "ranged", "strength": "0", "ability": "medic", "filename": "havekar_nurse_2", "count": "1" }'
+ ', { "name": "哈维卡走私者", "id": "110", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support", "count": "1" }'
+ ', { "name": "哈维卡走私者", "id": "111", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support_1", "count": "1" }'
+ ', { "name": "哈维卡走私者", "id": "112", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "muster", "filename": "havekar_support_2", "count": "1" }'
+ ', { "name": "艾达·艾敏·爱普·西夫尼", "id": "103", "deck": "scoiatael", "row": "ranged", "strength": "6", "ability": "", "filename": "ida", "count": "1" }'
+ ', { "name": "伊欧菲斯", "id": "20", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "iorveth", "count": "1" }'
+ ', { "name": "伊森格林·法欧提亚纳", "id": "19", "deck": "scoiatael", "row": "close", "strength": "10", "ability": "hero morale", "filename": "isengrim", "count": "1" }'
+ ', { "name": "玛哈坎守卫", "id": "115", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam", "count": "1" }'
+ ', { "name": "玛哈坎守卫", "id": "116", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_1", "count": "1" }'
+ ', { "name": "玛哈坎守卫", "id": "117", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_2", "count": "1" }'
+ ', { "name": "玛哈坎守卫", "id": "118", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_3", "count": "1" }'
+ ', { "name": "玛哈坎守卫", "id": "119", "deck": "scoiatael", "row": "close", "strength": "5", "ability": "", "filename": "mahakam_4", "count": "1" }'
+ ', { "name": "米尔瓦", "id": "101", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "morale", "filename": "milva", "count": "1" }'
+ ', { "name": "雷尔登", "id": "130", "deck": "scoiatael", "row": "ranged", "strength": "1", "ability": "", "filename": "riordain", "count": "1" }'
+ ', { "name": "萨琪亚", "id": "18", "deck": "scoiatael", "row": "ranged", "strength": "10", "ability": "hero", "filename": "saskia", "count": "1" }'
+ ', { "name": "托露薇尔", "id": "126", "deck": "scoiatael", "row": "ranged", "strength": "2", "ability": "", "filename": "toruviel", "count": "1" }'
+ ', { "name": "弗里赫德新兵", "id": "120", "deck": "scoiatael", "row": "ranged", "strength": "4", "ability": "", "filename": "vrihedd_cadet", "count": "1" }'
+ ', { "name": "弗里赫德老兵", "id": "113", "deck": "scoiatael", "row": "agile", "strength": "5", "ability": "", "filename": "vrihedd_brigade", "count": "1" }'
+ ', { "name": "弗里赫德老兵", "id": "114", "deck": "scoiatael", "row": "agile", "strength": "5", "ability": "", "filename": "vrihedd_brigade_1", "count": "1" }'
+ ', { "name": "亚伊文", "id": "105", "deck": "scoiatael", "row": "agile", "strength": "6", "ability": "", "filename": "yaevinn", "count": "1" }'
+ ', { "name": "狂战士", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "berserker", "filename": "berserker", "count": "1" }'
+ ', { "name": "碧尔娜·布兰", "id": "", "deck": "skellige", "row": "close", "strength": "2", "ability": "medic", "filename": "birna", "count": "1" }'
+ ', { "name": "蓝孩卢戈", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "", "filename": "blueboy", "count": "1" }'
+ ', { "name": "茜莉丝", "id": "", "deck": "skellige", "row": "close", "strength": "10", "ability": "hero muster", "filename": "cerys", "count": "1" }'
+ ', { "name": "布洛克瓦家族弓兵", "id": "", "deck": "skellige", "row": "ranged", "strength": "6", "ability": "", "filename": "brokva_archer", "count": "2" }'
+ ', { "name": "迪蒙家族海盗", "id": "", "deck": "skellige", "row": "ranged", "strength": "6", "ability": "scorch", "filename": "dimun_pirate", "count": "1" }'
+ ', { "name": "茜莉丝 — 德拉蒙家族持盾少女", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden", "count": "1" }'
+ ', { "name": "茜莉丝 — 德拉蒙家族持盾少女", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden_1", "count": "1" }'
+ ', { "name": "茜莉丝 — 德拉蒙家族持盾少女", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "bond", "filename": "shield_maiden_2", "count": "1" }'
+ ', { "name": "海玫家族诗人", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "heymaey", "count": "1" }'
+ ', { "name": "托达洛克家族铁匠", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "tordarroch", "count": "1" }'
+ ', { "name": "克拉特家族战士", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "bond", "filename": "craite_warrior", "count": "3" }'
+ ', { "name": "多纳·辛达", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "donar", "count": "1" }'
+ ', { "name": "德拉格·邦杜", "id": "", "deck": "skellige", "row": "siege", "strength": "2", "ability": "horn", "filename": "draig", "count": "1" }'
+ ', { "name": "艾尔米恩", "id": "", "deck": "skellige", "row": "ranged", "strength": "8", "ability": "hero mardroeme", "filename": "ermion", "count": "1" }'
+ ', { "name": "海姆达尔", "id": "", "deck": "skellige", "row": "close", "strength": "11", "ability": "hero", "filename": "hemdall", "count": "0" }'
+ ', { "name": "约阿玛", "id": "", "deck": "skellige", "row": "ranged", "strength": "10", "ability": "hero", "filename": "hjalmar", "count": "1" }'
+ ', { "name": "霍格尔·黑手", "id": "", "deck": "skellige", "row": "siege", "strength": "4", "ability": "", "filename": "holger", "count": "1" }'
+ ', { "name": "坎比", "id": "", "deck": "skellige", "row": "close", "strength": "0", "ability": "avenger_kambi", "filename": "kambi", "count": "1" }'
+ ', { "name": "轻型长船", "id": "", "deck": "skellige", "row": "ranged", "strength": "4", "ability": "muster", "filename": "light_longship", "count": "3" }'
+ ', { "name": "疯子卢戈", "id": "", "deck": "skellige", "row": "close", "strength": "6", "ability": "", "filename": "madmad_lugos", "count": "1" }'
+ ', { "name": "马德罗姆", "id": "", "deck": "special", "row": "", "strength": "", "ability": "mardroeme", "filename": "mardroeme", "count": "3" }'
+ ', { "name": "奥拉夫", "id": "", "deck": "skellige", "row": "agile", "strength": "12", "ability": "morale", "filename": "olaf", "count": "1" }'
+ ', { "name": "史凯利杰风暴", "id": "", "deck": "weather", "row": "", "strength": "", "ability": "storm rain fog", "filename": "storm", "count": "3" }'
+ ', { "name": "斯凡瑞吉", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "svanrige", "count": "1" }'
+ ', { "name": "变形后的维德卡尔", "id": "", "deck": "skellige", "row": "close", "strength": "14", "ability": "vildkarrl morale", "filename": "vildkaarl", "count": "0" }'
+ ', { "name": "变形后的年轻维德卡尔", "id": "", "deck": "skellige", "row": "ranged", "strength": "8", "ability": "vildkarrl bond", "filename": "young_vildkaarl", "count": "0" }'
+ ', { "name": "乌达瑞克", "id": "", "deck": "skellige", "row": "close", "strength": "4", "ability": "", "filename": "udalryk", "count": "1" }'
+ ', { "name": "战船", "id": "", "deck": "skellige", "row": "siege", "strength": "6", "ability": "bond", "filename": "war_longship", "count": "3" }'
+ ', { "name": "年轻狂战士", "id": "", "deck": "skellige", "row": "ranged", "strength": "2", "ability": "berserker", "filename": "young_berserker", "count": "3" }'
+ ', { "name": "克拉奇·安·克拉特", "id": "", "deck": "skellige", "row": "leader", "strength": "", "ability": "crach_an_craite", "filename": "crach_an_craite", "count": "0" }'
+ ', { "name": "布兰王", "id": "", "deck": "skellige", "row": "leader", "strength": "", "ability": "king_bran", "filename": "king_bran", "count": "0" }'
+ ', { "name": "席鲁", "id": "", "deck": "scoiatael", "row": "siege", "strength": "8", "ability": "scorch_s", "filename": "schirru", "count": "1" }'
+ ', { "name": "萝卜", "id": "", "deck": "neutral", "row": "close", "strength": "3", "ability": "", "filename": "roach", "count": "1" }'
+ ', { "name": "弩炮", "id": "", "deck": "realms", "row": "siege", "strength": "6", "ability": "", "filename": "ballista_1", "count": "1" }'
+ ']'
);